---

- name: Configure Fedora Workstation
  hosts: workstation
  vars_files:
    - vars/main.yml

  tasks:
    - name: Configure base settings for Fedora Workstation
      when: ansible_distribution == "Fedora"
      tags: common
      ansible.builtin.import_role:
        name: common

    - name: Install and configure appliations for Fedora Workstation
      when: ansible_distribution == "Fedora"
      tags: applications
      ansible.builtin.import_role:
        name: applications

    - name: Configure Gnome for Fedora Linux
      when: ansible_distribution == "Fedora"
      tags: gnome_settings
      ansible.builtin.import_role:
        name: gnome_settings